"""
environment.py — THE WORLD (step 1 of our RL project)
======================================================

In reinforcement learning there are two characters in a loop:

    AGENT  --acts-->  ENVIRONMENT  --(next state, reward)-->  AGENT

This file IS the environment: the maze, its walls, its rules, and its
scoring system. The agent (written in a later step) will only ever talk
to this file through two methods, following the standard "Gym API"
contract that every RL environment in the world uses:

    state        = env.reset()                      # start a new episode
    state, reward, done, info = env.step(action)    # take one action

There are two mazes in this project:

    classic  the hand-made maze below — your default on the first run
    random   generated by generate_random_maze(), saved to
             maze_random.json, and used from then on until you
             generate another one (the N key in play.py does this)

load_active_maze() tells everyone which one is "the" maze — play.py,
train.py and visualize.py all ask this file, so they can never disagree.

Try it yourself (random agent demo):

    python environment.py
"""

import json
import os
import random   # picks the random maze's shape AND the demo's moves
from collections import deque


# ==============================================================
# 1. WHAT THE MAZE IS MADE OF  (the "cells")
# ==============================================================
# The maze is a grid of cells. Each cell holds one of these codes.
# We use numbers (not words) because number grids are what ML code
# and numpy work with best — but the names keep the code readable.
EMPTY = 0   # open floor — the agent can walk here
WALL  = 1   # solid wall  — blocks movement
GOAL  = 2   # the target  — reaching it wins the episode  (+10)
PIT   = 3   # a trap      — falling in loses the episode   (-10)

# The maze itself, written as text so it's easy to SEE and edit.
#   . = empty   # = wall   S = start   G = goal   P = pit
# Row 0 is the TOP row. Column 0 is the LEFT column.
MAZE_MAP = [
    "S.#....",   # row 0
    "..#.##.",   # row 1
    ".......",   # row 2
    "###.###",   # row 3   <- the only door between top and bottom
    ".......",   # row 4
    ".#####.",   # row 5   <- only the left and right edges connect
    ".....PG",   # row 6   <- the pit sits in front of the goal!
]

# Every maze that lives in code, keyed by the name you pass to
# GridWorld(maze_name=...). The "random" maze is NOT here — it lives
# in maze_random.json (see the RANDOM MAZES section further down).
MAZES = {"classic": MAZE_MAP}

# One-character symbol for each cell type — used by render() so you
# can watch episodes play out as ASCII art (no window needed).
CELL_CHARS = {EMPTY: ".", WALL: "#", GOAL: "G", PIT: "P"}
START_CHAR = "S"   # shown only while the agent is still standing on it

MAZE_CHARS = {".": EMPTY, "#": WALL, "G": GOAL, "P": PIT, "S": EMPTY}


# ==============================================================
# 2. WHAT THE AGENT CAN DO  (the "action space")
# ==============================================================
# An RL agent picks an action as an INTEGER (0, 1, 2, 3) — numbers are
# what algorithms manipulate. The deltas below translate each action
# into a change of (row, col). Note the sign convention:
#   rows grow DOWNWARD  (+1 row = one step down)
#   cols grow RIGHTWARD (+1 col = one step right)
UP    = 0
DOWN  = 1
LEFT  = 2
RIGHT = 3

ACTION_DELTAS = {
    UP:    (-1,  0),
    DOWN:  (+1,  0),
    LEFT:  ( 0, -1),
    RIGHT: ( 0, +1),
}

# A friendly name for every action — purely cosmetic, used in logs
# so we can print "step 3: DOWN" instead of "step 3: 1".
ACTION_NAMES = {UP: "UP", DOWN: "DOWN", LEFT: "LEFT", RIGHT: "RIGHT"}

N_ACTIONS = len(ACTION_DELTAS)   # = 4, handy for the agent later


# ==============================================================
# 3. HOW THE WORLD SCORES  (the "reward function")
# ==============================================================
# This is the environment's judging system — the numbers the agent
# will chase (or avoid) when it learns. Changing these later is a
# one-line experiment: reward design is THE lever you pull when the
# agent learns something you didn't want.
GOAL_REWARD   = +10.0   # reached the goal   → win
PIT_REWARD    = -10.0   # fell into the pit  → loss
STEP_PENALTY  =  -0.1   # every move costs a little, so the agent
                        # learns to reach the goal FAST, not wander

MAX_STEPS = 100         # episode time limit. Without it, an agent
                        # that never reaches anything would loop
                        # forever and never get feedback.


# ==============================================================
# 4. THE ENVIRONMENT CLASS — the world in code
# ==============================================================
class GridWorld:
    """
    A 7x7 maze where an agent must reach the goal without falling
    into the pit, following the Gym API contract:

        state             = reset()
        state, reward, done, info = step(action)
    """

    def __init__(self, maze_name="classic"):
        """Build the static parts of the world (walls, goal, pit...).

        __init__ runs ONCE when the object is created — the maze
        layout never changes, so it's parsed here, not on every reset.

        Args: maze_name — "classic" (hand-made), "random" (the saved
              maze_random.json), or any other name in the MAZES dict.
        """
        # --- which maze are we building? -----------------------------
        if maze_name in MAZES:
            rows = MAZES[maze_name]
        elif maze_name == "random":
            rows = load_random_maze()
        else:
            available = ", ".join(sorted(MAZES) + ["random"])
            raise ValueError(
                f"Unknown maze {maze_name!r} — available: {available}"
            )
        self.maze_name = maze_name
        # Keep the text rows around: charts and logs need them later.
        self.maze_rows = list(rows)

        # --- parse the text map into a 2D grid -----------------------
        # grid[row][col] = cell code. This lookup table is how we ask
        # "what's at (row, col)?" fast. A bad character (corrupt file)
        # should fail with a clear message, not a raw KeyError.
        widths = {len(row) for row in rows}
        if len(widths) != 1:
            raise ValueError(
                f"maze rows have different lengths: {sorted(widths)}"
            )
        try:
            self.grid = [
                [MAZE_CHARS[ch] for ch in row] for row in rows
            ]
        except KeyError as bad:
            raise ValueError(
                f"maze contains an unknown character {bad.args[0]!r} "
                f"— use only . # S G P"
            ) from None
        self.rows = len(self.grid)         # 7
        self.cols = len(self.grid[0])      # 7

        # --- remember where the agent starts -------------------------
        # We SCAN the text for 'S' instead of assuming (0, 0): a random
        # maze puts the start wherever it likes, and so could any maze
        # you add to MAZES tomorrow.
        self.start_pos = None
        for r, row in enumerate(rows):
            for c, ch in enumerate(row):
                if ch == "S":
                    self.start_pos = (r, c)
                    break
            if self.start_pos is not None:
                break
        if self.start_pos is None:
            raise ValueError("maze has no start cell 'S'")

        # Dynamic state — these change as the episode plays out,
        # so they start unset and are (re)initialized by reset().
        self.agent_pos = None   # where the agent currently stands
        self.steps = 0          # how many actions taken this episode
        self.done = False       # has the episode ended?

    # ----------------------------------------------------------
    # 4a. reset() — start a fresh episode
    # ----------------------------------------------------------
    def reset(self):
        """
        Put everything back to square one and return the initial state.

        In RL an "episode" = one full attempt (start → win/lose).
        The agent calls this AFTER every finished episode.

        Returns: state — the agent's current position as (row, col).
                 For our maze the state IS the position: the agent
                 knows exactly where it is (fully observable).
        """
        self.agent_pos = self.start_pos
        self.steps = 0
        self.done = False
        return self.agent_pos

    # ----------------------------------------------------------
    # 4b. step(action) — the heart of the environment
    # ----------------------------------------------------------
    def step(self, action):
        """
        Apply one action and see what the world does in return.

        Args:    action — integer 0..3 (UP/DOWN/LEFT/RIGHT)
        Returns: (state, reward, done, info)

            state  — the agent's new position after the action
            reward — a single float: immediate judgement of that
                     action (+10 win / -10 loss / -0.1 ordinary step)
            done   — True if the episode is over (win, loss, or timeout)
            info   — a dict of extra facts for humans/logging;
                     the agent does NOT learn from it
        """
        # --- Guard rails -------------------------------------------------
        # Calling step() after the episode ended is a classic bug that
        # produces confusing errors later, so we fail loudly and early.
        if self.done:
            raise RuntimeError(
                "Episode is over — call reset() before step()."
            )
        if action not in ACTION_DELTAS:
            raise ValueError(
                f"Invalid action {action!r}: use 0=UP, 1=DOWN, 2=LEFT, 3=RIGHT"
            )

        # --- 1. Move the agent (transition dynamics) ---------------------
        # Compute where the action WOULD take us...
        dr, dc = ACTION_DELTAS[action]
        row, col = self.agent_pos
        new_pos = (row + dr, col + dc)

        # ...then check the world's rules. Deterministic movement means:
        # same action + same state = same result, every single time.
        bumped = False
        if not self._inside(new_pos) or self._cell(new_pos) == WALL:
            # Hit a wall or the edge → the agent stays put.
            # It still "spent" the turn (and pays the step penalty),
            # so bumping into walls is discouraged, not free.
            new_pos = self.agent_pos
            bumped = True

        self.agent_pos = new_pos
        self.steps += 1

        # --- 2. Score the outcome (reward function) ----------------------
        cell = self._cell(self.agent_pos)
        reward = STEP_PENALTY        # default: every step costs a little
        done = False
        reason = None                # explains WHY the episode ended

        if cell == GOAL:
            reward = GOAL_REWARD     # win!
            done = True
            reason = "goal"
        elif cell == PIT:
            reward = PIT_REWARD      # loss!
            done = True
            reason = "pit"
        elif self.steps >= MAX_STEPS:
            # Ran out of time without winning — still -0.1 for the
            # step, but the episode is forcibly closed ("truncated"
            # in Gym terminology). Counted as a failure.
            done = True
            reason = "timeout"

        # --- 3. Close the episode ----------------------------------------
        if done:
            self.done = True

        # info is a side-channel for humans: why it ended, whether we
        # bumped a wall, how many steps we've taken. The agent ignores it.
        info = {"reason": reason, "bumped": bumped, "steps": self.steps}

        return self.agent_pos, reward, done, info

    # ----------------------------------------------------------
    # 4c. render() — watch the world without a window
    # ----------------------------------------------------------
    def render(self):
        """
        Print the maze as ASCII art, with 'A' marking the agent.

        A quick sanity-check tool: runs anywhere, no GUI. The pretty
        pygame window comes in part C — this is the debugger version.
        """
        lines = []
        for r in range(self.rows):
            row_cells = []
            for c in range(self.cols):
                if (r, c) == self.agent_pos:
                    row_cells.append("A")           # the agent wins
                elif (r, c) == self.start_pos and self.grid[r][c] == EMPTY:
                    row_cells.append(START_CHAR)    # remember the start
                else:
                    row_cells.append(CELL_CHARS[self.grid[r][c]])
            lines.append(" ".join(row_cells))
        print("\n".join(lines))

    # ----------------------------------------------------------
    # 4d. Small helpers (used by step/render)
    # ----------------------------------------------------------
    def _inside(self, pos):
        """True if (row, col) is within the grid borders."""
        r, c = pos
        return 0 <= r < self.rows and 0 <= c < self.cols

    def _cell(self, pos):
        """What kind of cell lives at (row, col)?"""
        r, c = pos
        return self.grid[r][c]


# ==============================================================
# 5. RANDOM MAZES — generated once, kept forever
# ==============================================================
# Where the current random maze lives on disk. When this file does
# NOT exist, the classic maze above is the active one — so a fresh
# clone of the project always starts on classic.
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ACTIVE_MAZE_FILE = os.path.join(BASE_DIR, "maze_random.json")

# The characters a maze may contain (used to validate a saved file).
VALID_MAZE_CHARS = set(".#SGP")


def _carve(rows, cols):
    """Carve a perfect maze of walls into a rooms-and-corridors grid.

    Works on odd sizes only: cells at EVEN (row, col) are "rooms",
    everything between them starts as a wall. A depth-first walk
    knocks down one wall per newly reached room, which guarantees
    every floor cell is connected to every other (a "perfect" maze —
    there is exactly one path between any two rooms, no loops).

    Returns the maze as a list of lists of "#" and "." characters.
    """
    grid = [["#"] * cols for _ in range(rows)]
    start_room = random.randrange(0, rows, 2), random.randrange(0, cols, 2)
    grid[start_room[0]][start_room[1]] = "."
    visited = {start_room}
    stack = [start_room]

    while stack:
        r, c = stack[-1]
        neighbours = []
        for dr, dc in ((-2, 0), (2, 0), (0, -2), (0, 2)):
            nr, nc = r + dr, c + dc
            if 0 <= nr < rows and 0 <= nc < cols and (nr, nc) not in visited:
                # The cell strictly BETWEEN the rooms (r+dr//2, c+dc//2)
                # is the wall we'd have to knock down to get there.
                neighbours.append((nr, nc, r + dr // 2, c + dc // 2))
        if not neighbours:
            stack.pop()          # dead end: backtrack
            continue
        nr, nc, wr, wc = random.choice(neighbours)
        grid[wr][wc] = "."      # knock down the wall
        grid[nr][nc] = "."      # step into the new room
        visited.add((nr, nc))
        stack.append((nr, nc))

    return grid


def _path_cells(rows, avoid_pit):
    """Breadth-first search: one shortest path from S to G, or [].

    BFS is the standard "is there a way?" algorithm: flood outward
    from the start one step at a time, remember where each wave came
    from, and rebuild the route once the goal is reached. With
    avoid_pit=True the pit counts as deadly (blocked), which is
    exactly the question "can the agent WIN here?".
    """
    start = goal = None
    for r, row in enumerate(rows):
        for c, ch in enumerate(row):
            if ch == "S":
                start = (r, c)
            elif ch == "G":
                goal = (r, c)
    if start is None or goal is None:
        return []

    def walkable(r, c):
        if not (0 <= r < len(rows) and 0 <= c < len(rows[0])):
            return False
        ch = rows[r][c]
        if ch == "#":
            return False
        if avoid_pit and ch == "P":
            return False
        return True

    queue = deque([start])
    came_from = {start: None}
    while queue:
        r, c = queue.popleft()
        if (r, c) == goal:
            path = []
            node = goal
            while node is not None:        # walk back to the start
                path.append(node)
                node = came_from[node]
            return path[::-1]
        for dr, dc in ((-1, 0), (1, 0), (0, -1), (0, 1)):
            nr, nc = r + dr, c + dc
            if (nr, nc) not in came_from and walkable(nr, nc):
                came_from[(nr, nc)] = (r, c)
                queue.append((nr, nc))
    return []


def path_exists(rows, avoid_pit=True):
    """True if the agent can win this maze (S -> G, pit avoided)."""
    return bool(_path_cells(rows, avoid_pit=avoid_pit))


def generate_random_maze(rows=7, cols=7, max_attempts=50):
    """Build a fresh 7x7 maze that is fair: solvable AND losable.

    Recipe:
      1. carve a perfect maze (every floor cell connected),
      2. drop S and G on two random floor cells,
      3. find the unique safe path between them,
      4. put the pit on a floor cell OFF that path — so a careless
         agent can still walk into it (losable), while a careful one
         always has a way around it (solvable).

    If step 4 finds no free cell (the path used up the whole maze,
    which is rare), we throw the maze away and start over.
    """
    if rows % 2 == 0 or cols % 2 == 0:
        raise ValueError("random maze sizes must be odd (e.g. 7x7)")

    for _ in range(max_attempts):
        grid = _carve(rows, cols)
        floors = [(r, c)
                  for r in range(rows) for c in range(cols)
                  if grid[r][c] == "."]
        if len(floors) < 3:
            continue
        start, goal = random.sample(floors, 2)
        grid[start[0]][start[1]] = "S"
        grid[goal[0]][goal[1]] = "G"

        text = ["".join(row) for row in grid]
        safe_path = set(_path_cells(text, avoid_pit=False))
        safe_path.update((start, goal))
        free = [p for p in floors if p not in safe_path]
        if not free:
            continue                       # path ate the maze: retry
        pit = random.choice(free)
        grid[pit[0]][pit[1]] = "P"

        text = ["".join(row) for row in grid]
        if path_exists(text):              # belt and braces
            return text

    raise RuntimeError(
        f"could not generate a fair {rows}x{cols} maze "
        f"in {max_attempts} attempts"
    )


def save_random_maze(rows, path=None):
    """Write the maze to disk so it survives across program runs."""
    if path is None:
        path = ACTIVE_MAZE_FILE
    with open(path, "w", encoding="utf-8") as f:
        json.dump(list(rows), f, indent=1)


def load_random_maze(path=None):
    """The saved random maze — generate and save one if none exists yet.

    This file is the SINGLE SOURCE OF TRUTH for "the random maze":
    play.py, train.py and visualize.py all read it, so the maze you
    play is always the maze the agent trains on.
    """
    if path is None:
        path = ACTIVE_MAZE_FILE
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            rows = json.load(f)
        if not isinstance(rows, list) or not rows:
            raise ValueError(
                f"{os.path.basename(path)} is corrupt — delete it "
                f"and press N to generate a new maze"
            )
        return rows
    rows = generate_random_maze()
    save_random_maze(rows, path)
    return rows


def load_active_maze(path=None):
    """Which maze does everything run on right now?

    Returns (name, rows): "classic" on a first run (no maze_random.json
    yet), "random" from then on — until you generate another one.
    """
    if path is None:
        path = ACTIVE_MAZE_FILE
    if os.path.exists(path):
        return "random", load_random_maze(path)
    return "classic", MAZE_MAP


# ==============================================================
# 6. DEMO — a RANDOM agent playing one episode
# ==============================================================
# The environment is useless until we can run episodes through it.
# This demo plays badly on purpose (random moves) — its job is to
# prove the rules work: walls block, scoring fires, episodes end.
if __name__ == "__main__":
    env = GridWorld()

    state = env.reset()          # fresh episode
    total_reward = 0.0           # cumulative score, like a game total
    print("=== Random agent episode ===")
    env.render()

    while True:
        # Random policy: pick one of the 4 actions, no thinking involved.
        # (Later, the Q-learning agent will replace this line.)
        action = random.randint(0, N_ACTIONS - 1)

        state, reward, done, info = env.step(action)
        total_reward += reward

        print(
            f"\naction={ACTION_NAMES[action]:<5}  "
            f"reward={reward:+.1f}  "
            f"state={state}  "
            f"{'WALL BUMP - stayed put' if info['bumped'] else ''}"
        )
        env.render()

        if done:
            break

    # ------------------------------------------------------------ #
    print("\n=== Episode finished ===")
    print(f"outcome : {info['reason']}")        # goal / pit / timeout
    print(f"steps   : {info['steps']} / {MAX_STEPS}")
    print(f"reward  : {total_reward:+.1f}")
